### ISSUE TITLE
如何批量翻译?

### ISSUE THREAD

**Issue by aaawhz** [Selection-Translator/translation.js#25]
比如有一个对象需要翻译`{"mimaxiugaishibaiqingzhongshi" :  "密码修改失败，请重试" ,
"qingshuruyuanmima" :  "请输入原密码" ,
"mimabixuweiwei" :  "密码必须为6-30位" ,
"qingshuruxinmima" :  "请输入新密码" ,}`

怎么批量翻译了.

**Comment by lmk123** [comment]
这不应该是业务代码中需要实现的功能吗？

**Comment by aaawhz** [comment]
批量翻译 , 比如有100个中文, 能不能作为一个数组进行查询,  查询结果也返回一个数组, 对应这100条中文的英文翻译

**Comment by aaawhz** [comment]
100个中文句子 转换 为 100个对应的英文句子.

**Comment by lmk123** [comment]
没有内置这个功能，但是你循环一下数组逐条翻译应该不会很难吧

**Comment by icepy** [comment]
> 没有内置这个功能，但是你循环一下数组逐条翻译应该不会很难吧

貌似调用翻译接口有频率限制，我这边测试了一下，之后就一直报错了：

```js
Error
    at getError (/Users/s/github/farm-platfrom/packages/farm-translation/node_modules/translation.js/dist/tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (/Users/s/github/farm-platfrom/packages/farm-translation/node_modules/translation.js/dist/tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
```

**Comment by icepy** [comment]
> 没有内置这个功能，但是你循环一下数组逐条翻译应该不会很难吧

貌似调用翻译接口有频率限制，我这边测试了一下，之后就一直报错了：

```js
Error
    at getError (/Users/s/github/farm-platfrom/packages/farm-translation/node_modules/translation.js/dist/tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (/Users/s/github/farm-platfrom/packages/farm-translation/node_modules/translation.js/dist/tjs.node.common.js:124:24)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
```
