### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by lazybonee** [Selection-Translator/translation.js#37]
`google.translate('test').then(result => {
    console.log(result) // result 的数据结构见下文
})`
用谷歌有道和百度都进行了测试，但是都报网络连接超时错误。错误信息如下：
PS F:\test> node run.js
(node:18476) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 106.39.162.57:443
    at getError (F:\test\node_modules\translation.js\dist\tjs.node.common.js:83:13)
    at ClientRequest.<anonymous> (F:\test\node_modules\translation.js\dist\tjs.node.common.js:149:20)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lmk123** [comment]
提供以下 runl.js 的内容？

**Comment by lazybonee** [comment]
经过检查发现是http代理的原因，公司内部默认无法访问外部接口，已经通过设置代理解决了~
