### ISSUE TITLE
微信云函数中调用百度翻译失败

### ISSUE THREAD

**Issue by syupo** [Selection-Translator/translation.js#51]
在微信云函数中使用translation.js（>=0.7.5）时，如果使用百度翻译则直接报错（有道和谷歌没有问题），错误信息如下：

    at getError (/var/user/node_modules/translation.js/dist/tjs.node.common.js:83:13)

    at ClientRequest.<anonymous> (/var/user/node_modules/translation.js/dist/tjs.node.common.js:124:24)

    at Object.onceWrapper (events.js:315:30)

    at emitOne (events.js:116:13)

    at ClientRequest.emit (events.js:211:7)

    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)

    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)

    at TLSSocket.socketOnData (_http_client.js:440:20)

    at emitOne (events.js:116:13)

    at TLSSocket.emit (events.js:211:7)

    抛错的代码位置（进入了响应码非200的分支）：

    `var req = (urlObj.protocol === 'https:' ? https.request : http.request)(httpOptions, function (res) {
         // 内置的翻译接口都以 200 作为响应码，所以不是 200 的一律视为错误
         if (**res.statusCode !== 200**) {
             reject(getError("API_SERVER_ERROR" /* API_SERVER_ERROR */));
             return;
         }
    ......
    });`

如果在本地环境下，使用Express+浏览器请求则一切正常；
如果使用小程序开发工具在本地调试微信云函数则也正常；
初步怀疑是云函数环境下发起请求时，百度翻译API做了拦截或什么的（因为1月份早些时候还OK）

以上，烦请作者酌情调查。

**Comment by lmk123** [comment]
你能在这里加一行代码打印出来看看在微信云函数中，百度的接口返回了什么吗？

**Comment by syupo** [comment]
> 你能在这里加一行代码打印出来看看在微信云函数中，百度的接口返回了什么吗？

补充：微信云函数运行环境为Nodejs8.9，本地Express运行环境为Nodejs10.14.1

1. 回调函数中添加打印输出代码，
**console.log(`状态码: ${res.statusCode}`, `状态消息: ${res.statusMessage}`);**

2. 得到的打印日志为（输出了两次响应状态码）：
2020-03-06T11:21:51.778Z	ad436f82-5f9c-11ea-96c2-525400090c2c	**状态码: 200 状态消息: OK**
2020-03-06T11:21:52.050Z	ad436f82-5f9c-11ea-96c2-525400090c2c	**状态码: 401 状态消息: Unauthorized**
Error

    at getError (/var/user/node_modules/translation.js/dist/tjs.node.common.js:83:13)

    at ClientRequest.<anonymous> (/var/user/node_modules/translation.js/dist/tjs.node.common.js:125:24)

    at Object.onceWrapper (events.js:315:30)

    at emitOne (events.js:116:13)

    at ClientRequest.emit (events.js:211:7)

    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)

    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)

    at TLSSocket.socketOnData (_http_client.js:440:20)

    at emitOne (events.js:116:13)

    at TLSSocket.emit (events.js:211:7)
